version: '2'

services:
  mysql-master:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=t5496ssf55d6llfge
      - MYSQL_USER=notifacil-user
      - MYSQL_PASSWORD=t5496d6458sfge
      - MYSQL_DATABASE=notifacil-bd
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password